# Generated by Django 5.2 on 2026-05-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='LocalityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_rating', models.IntegerField(blank=True, null=True)),
                ('commercial_rating', models.IntegerField(blank=True, null=True)),
                ('market_dist_km', models.FloatField(blank=True, null=True)),
                ('transit_dist_km', models.FloatField(blank=True, null=True)),
                ('best_use_suggestions', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('locality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='properties.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.locality')),
            ],
        ),
    ]
