# Generated by Django 5.2 on 2026-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localityprofile',
            name='infrastructure_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='localityprofile',
            name='nearby_places',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
